version: '3'
services:

  web:
    container_name: php-apache
    image: php:8.2.1-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  mysql:
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "3306:3306"